#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("overlay.mobile.droid.Resource", IsApplication=true)]

namespace overlay.mobile.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_pseaapp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_pseaapp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_pseaapp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_pseaapp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_pseaapp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_pseaapp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_pseaapp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_focused_pseaapp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_pressed_pseaapp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_pseaapp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_pseaapp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_pseaapp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int error2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int list_focused_pseaapp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int list_pressed_pseaapp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int menu_dropdown_panel_pseaapp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int my_progress = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int progress_bg_pseaapp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int progress_horizontal_pseaapp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int progress_primary_pseaapp = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int progress_secondary_pseaapp = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int PSEA_app_launchicon_48 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int resultsetnext = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int selectable_background_pseaapp = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int slideout = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int spinner3black = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int spinner_ab_default_pseaapp = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int spinner_ab_disabled_pseaapp = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int spinner_ab_focused_pseaapp = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int spinner_ab_pressed_pseaapp = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int spinner_background_ab_pseaapp = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int splashpage = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_indicator_ab_pseaapp = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_selected_focused_pseaapp = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_selected_pressed_pseaapp = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_selected_pseaapp = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_unselected_focused_pseaapp = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tab_unselected_pressed_pseaapp = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tab_unselected_pseaapp = 2130837543;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int mySwitchControl = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int myswitch = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int progressBar1 = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int relativeLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int txtTitle = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BlankLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DisabledLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoadingLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int switch_layout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int SwitchMenuItem = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int databaseVersion = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int skipsplash = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int ActionBar_Solid_Pseaapp = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ActionBar_Transparent_Pseaapp = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int ActionBarTabStyle_Pseaapp = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int ActionButton_CloseMode_Pseaapp = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int DropDownListView_Pseaapp = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int DropDownNav_Pseaapp = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int PopupMenu_Pseaapp = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int ProgressBar_Pseaapp = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Pseaapp = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int Theme_Pseaapp_Widget = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
